In [1]:
import numpy as np
import pandas as pd

1) From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
2) Replace missing values in Min.Price and Max.Price columns with their respective mean (check documentation).
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
3) How to get the rows of a dataframe with row sum > 100?
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
4) Create a 4x4 NumPy array filled with random integers between 1 and 100. Then, reshape this array into two separate 2D arrays, where one represents the rows and the other represents the columns. Write a function, preferably using a lambda function, to calculate the sum of each row and each column separately, and return the results as two separate NumPy arrays

In [20]:
# Q1
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
filtered = df.iloc[::20][['Manufacturer', "Model", 'Type']]
filtered

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

In [37]:
# Q2
min_mean = df['Min.Price'].mean()
max_mean = df['Max.Price'].mean()

df['Min.Price'] = df['Min.Price'].fillna(min_mean)
df['Max.Price'] = df['Max.Price'].fillna(max_mean)
# inplace=True
df

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small  12.900000   15.9        NaN      25.0   
1           NaN   Legend  Midsize  29.200000   33.9        NaN      18.0   
2          Audi       90  Compact  25.900000   29.1        NaN      20.0   
3          Audi      100  Midsize  17.118605   37.7        NaN      19.0   
4           BMW     535i  Midsize  17.118605   30.0        NaN      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van  16.600000   19.7        NaN      17.0   
89   Volkswagen   Passat  Compact  17.600000   20.0        NaN      21.0   
90   Volkswagen  Corrado   Sporty  22.900000   23.3        NaN      18.0   
91        Volvo      240  Compact  21.800000   22.7        NaN      21.0   
92          NaN      850  Midsize  24.800000   26.7        NaN      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                 NaN      Front  ...        5.0   177.0   
1          25.0  Driver & Passenger      Front  ...        5.0   195.0   
2          26.0         Driver only      Front  ...        5.0   180.0   
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4          30.0                 NaN       Rear  ...        4.0   186.0   
..          ...                 ...        ...  ...        ...     ...   
88         21.0                 NaN      Front  ...        7.0   187.0   
89         30.0                 NaN      Front  ...        5.0   180.0   
90         25.0                 NaN      Front  ...        4.0   159.0   
91         28.0         Driver only       Rear  ...        5.0   190.0   
92         28.0  Driver & Passenger      Front  ...        5.0   184.0   

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0   
1       115.0   71.0         38.0           30.0          15.0  3560.0   
2       102.0   67.0         37.0           28.0          14.0  3375.0   
3       106.0    NaN         37.0           31.0          17.0  3405.0   
4       109.0   69.0         39.0           27.0          13.0  3640.0   
..        ...    ...          ...            ...           ...     ...   
88      115.0   72.0         38.0           34.0           NaN  3960.0   
89      103.0   67.0         35.0           31.5          14.0  2985.0   
90       97.0   66.0         36.0           26.0          15.0  2810.0   
91      104.0   67.0         37.0           29.5          14.0  2985.0   
92      105.0   69.0         38.0           30.0          15.0  3245.0   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
..      ...                 ...  
88      NaN  Volkswagen Eurovan  
89  non-USA   Volkswagen Passat  
90  non-USA  Volkswagen Corrado  
91  non-USA           Volvo 240  
92  non-USA           Volvo 850  

[93 rows x 27 columns]

In [51]:
# Q3 
# How to get the rows of a dataframe with row sum > 100?
# df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

df =pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
df[df.sum(axis=1) > 100]

0   1   2   3
0   24  36  35  17
1   26  30  25  28
5   20  30  26  34
6   18  28  27  31
7   32  33  33  10
9   33  27  37  14
10  12  33  38  35
12  34  25  21  25
14  34  38  26  13

In [62]:
# Q4
# Create a 4x4 NumPy array filled with random integers between 1 and 100. 
# Then, reshape this array into two separate 2D arrays, where one represents the rows and the other represents the columns. 
# Write a function, preferably using a lambda function, to calculate the sum of each row and each column separately, and return the results as two separate NumPy arrays

arr = np.random.randint(1,101,size=(4,4))
rows, cols = arr.shape
sum_func = lambda i : np.array([i.sum(axis=0), i.sum(axis=1)])
row_sum = sum_func(arr.reshape(rows,-1))
col_sum = sum_func(arr.reshape(-1,cols))
print(row_sum)
print(col_sum)

[[159 161 173 262]
 [191 228 218 118]]
[[159 161 173 262]
 [191 228 218 118]]
